version: '3'
services:
  nginx:
    image: dockerhub nginx-4dvop nginximg
    ports:
      - "8080:8080"
  haproxy:
    image: dockerhub haproxy-4dvop haproxyimg
    ports:
      - "80:80"
    depends_on:
      - nginx
